// Morita Protocol - Cairo Contracts
// Workspace entry point - all packages are in separate folders

// Packages:
// - verifier: Honk verifier contract (auto-generated by Garaga)
`// - morita_invoice: Main invoice management contract