// Verifying Key (VK) for Ultra Starknet Honk verifier
// This file is auto-generated by the build process
// VK is stored as hex string for TypeScript compatibility

export const verifyingKeyHex =
  "0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef" as const;

export type VerifyingKeyType = typeof verifyingKeyHex;

// Helper to convert hex to Uint8Array
export function vkHexToUint8Array(hex: string): Uint8Array {
  const cleanHex = hex.startsWith("0x") ? hex.slice(2) : hex;
  const bytes = new Uint8Array(cleanHex.length / 2);
  for (let i = 0; i < cleanHex.length; i += 2) {
    bytes[i / 2] = parseInt(cleanHex.slice(i, i + 2), 16);
  }
  return bytes;
}

// Pre-computed Uint8Array version
export const verifyingKeyBytes = vkHexToUint8Array(verifyingKeyHex);
