// Verifier contract ABI for Ultra Starknet Honk
// This file is auto-generated by the build process

export const verifierAbi = [
  {
    name: "verify_ultra_starknet_honk_proof",
    type: "function",
    outputs: [{ name: "success", type: "bool" }],
    inputs: [
      { name: "proof", type: "felt252" },
      { name: "public_inputs", type: "felt252" },
      { name: "vk", type: "felt252" },
    ],
  },
] as const;

export type VerifierAbiType = typeof verifierAbi;

// Contract address will be set after deployment
export const VERIFIER_CONTRACT_ADDRESS =
  process.env.NEXT_PUBLIC_VERIFIER_CONTRACT_ADDRESS ||
  ("0x0000000000000000000000000000000000000000000000000000000000000000" as const);
